### ISSUE TITLE
Iteration 1 - MVP

### ISSUE THREAD

**Issue by moranas** [alonaya/Pina-Chama#27]

**Comment by ItamarShDev** [comment]
have you use unit testing or any type of testing?

**Comment by moranadler** [comment]
We have done extensive testing by ourselves.

**Comment by ItamarShDev** [comment]
@moranas is it documented somewhere?
Please add a testing section in iter1 page so i could grade you and close this :)

**Comment by ItamarShDev** [comment]
cant find your [code reviews](http://jce-il.github.io/se-class16b/morea/planning/experience-project6-iterations.html#section-14)

**Comment by moranadler** [comment]
The tests are documented, we added the testing section as requested. 
[Testing document](../raw/master/docs/test-section.docx)
You can also find the link in iteration 1 in the wiki page.
