### ISSUE TITLE
brought up at MVP class review #27

### ISSUE THREAD

**Issue by alonaya** [alonaya/Pina-Chama#28]
- Corrections for the iteration summary: delete Node.js, create table for planning facing execution. 
- Add issue for bugs (with tags)
- Create page for team assignment division - table for each iteration

**Comment by ItamarShDev** [comment]
good!
waiting to the team page to be done
please mark it as done and tag me at the end :)

**Comment by hilaop** [comment]
@ItamarShDev 
we added the team page :)
