### ISSUE TITLE
Code review - View messages for all users

### ISSUE THREAD

**Issue by hilaop** [alonaya/Pina-Chama#38]
- [ ] the code of loading the messages for every type of user is split by few files.  
  In my opinion it would be a good idea to unite it to one single page and use cases to load every type of messages - we can actually remove all the main pages for every user type and create one main page for all user types - every type of user will see the right messages.

**Comment by To0oM** [comment]
great idea, the messages area is the only reason we have a seperated files, we can unite it to one single file and by using the 'user type' attribute - load the right messages with the right function.
I afraid it can take a while to do the changes, I prefer to do this at the end of the next iteration(if we have some extra time)

**Comment by To0oM** [comment]
unfortunately we don't have time to make this change, we leave it as it is - a main page for every user type.
