### ISSUE TITLE
brought up at SRS class review

### ISSUE THREAD

**Issue by alonaya** [alonaya/Pina-Chama#4]
- fix the UML - delete the DB(as a user)
- SRS review with client added

**Comment by moranas** [comment]
הודעת דוא"ל זו נשלחה ממחשב נקי מווירוסים המוגן על ידי Avast.‏
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-03-21 15:42 GMT+02:00 alonaya <notifications@github.com>:

**Comment by hilaop** [comment]
SRS document fixed

**Comment by ItamarShDev** [comment]
:+1:
