### ISSUE TITLE
Code review - iteration 3

### ISSUE THREAD

**Issue by hilaop** [alonaya/Pina-Chama#42]
in the shifts / cakes arrangement tabs style, you added some general css styles to the 'a links', I think it would be better if you add an id or class to the links and apply the style on the id/class instead of changing the style of all 'a links', it may cause a problem in the future

**Comment by To0oM** [comment]
I will add an id or class and change the general style later in this iteration.

**Comment by To0oM** [comment]
I fixed this problem, it have a separate classes and the 'a links' for the rest of the site is back to normal.
